from flask import Flask, render_template, session, request, redirect, url_for, jsonify
from flask import Flask, send_from_directory
import random

app = Flask(__name__)
app.secret_key = "cayman_quiz_secret_2026"

# ─────────────────────────────────────────────
# FULL QUESTION BANK  (PPT Q1-50  +  extra questions from second source)
# ─────────────────────────────────────────────
ALL_QUESTIONS = [
    # ── PPT SECTION 1 (Q1-25) ──────────────────
    {"id": 1,  "title": "Where would the vehicle license coupon be affixed on a vehicle?",
     "options": ["To the front windscreen to the center, not obstructing the driver.",
                 "To the rear windscreen to the left within six (6) inches of the edge.",
                 "To the right side of the front windscreen so that it can be clearly seen.",
                 "To the front windscreen within six (6) inches of the left edge."], "correct": 3},
    {"id": 2,  "title": "At what age can a person legally register a motor vehicle?",
     "options": ["21 yrs","18 yrs","17 yrs","As soon as they can afford a vehicle."], "correct": 1},
    {"id": 3,  "title": "When a vehicle is sold, the details of the new owner must be re-registered within:",
     "options": ["14 days of the transfer.","21 days of the transfer.","Immediately at the time of the transfer.","Anytime or at the convenience of the new owner."], "correct": 0},
    {"id": 4,  "title": "When a vehicle is scrapped or exported from the islands, who should be informed?",
     "options": ["The Customs department.","The Environment department.","The Licensing department.","The Planning department."], "correct": 2},
    {"id": 5,  "title": "A vehicle license may be taken out for:",
     "options": ["Three, six or twelve months.","Not less than six months.","One year, two years, or three years.","Not more than three (3) months."], "correct": 0},
    {"id": 6,  "title": "What three requirements must be met for a vehicle to legally operate on the road?",
     "options": ["The owner must pay for inspection, transfer and licensing.",
                 "The vehicle must be inspected, licensed and insured.",
                 "The vehicle must be serviced, inspected and roadworthy.",
                 "No specific requirements are necessary."], "correct": 1},
    {"id": 7,  "title": "At what age must a person be to drive: a motorcycle <125cc; a regular car or station wagon; a rental car?",
     "options": ["17 yrs","18 yrs","19 yrs","21 yrs"], "correct": 1},
    {"id": 8,  "title": "At what age must a person be to drive: a pickup less than three tons capacity; any other vehicle?",
     "options": ["17 yrs","18 yrs","19 yrs","21 yrs"], "correct": 1},
    {"id": 9,  "title": "At what age must a person be to drive a motorcycle with an engine exceeding 125cc?",
     "options": ["17 yrs","18 yrs","19 yrs","21 yrs"], "correct": 3},
    {"id": 10, "title": "What proof must a driver show before riding a motorcycle with an engine larger than 125cc?",
     "options": ["That he owns a motorcycle with an engine greater than 125cc.",
                 "That he has ridden a smaller motorcycle with an engine larger than 125cc.",
                 "That he has ridden a smaller motorcycle, less than 125cc for at least two years.",
                 "That he is mature and has a good driving record."], "correct": 2},
    {"id": 11, "title": "Which statement is correct regarding allowing others to drive your vehicle?",
     "options": ["The owner may allow a person below the driving age if they have a valid license.",
                 "The owner can allow an adult to drive as long as written permission is given.",
                 "The law permits any person with a valid license to drive any group of vehicle.",
                 "The owner commits a serious offence if he permits a person to drive a vehicle they are not licensed or insured for."], "correct": 3},
    {"id": 12, "title": '"L" plates must be displayed on the front and rear of the vehicle:',
     "options": ["At any time the driving instructor is driving the vehicle.",
                 "At all times whether the vehicle is being driven or not.",
                 '"L" plates are optional and are only there to alert other road users.',
                 "Only when a provisional license holder is driving the vehicle."], "correct": 3},
    {"id": 13, "title": '"L" plates must be displayed on:',
     "options": ["Only when a provisional license holder is driving the vehicle.",
                 "The front driver's side and rear passenger side.",
                 "The trunk and bonnet of the vehicle.",
                 "The rear bumper only."], "correct": 1},
    {"id": 14, "title": "It is permitted to leave a vehicle unattended when running:",
     "options": ["When you are sure to return in 5 minutes or less.",
                 "When you are in a safe parking zone.",
                 "When your child is still in the car and it is raining.",
                 "The vehicle should never be left unattended when running."], "correct": 3},
    {"id": 15, "title": "An overtaking vehicle must always pass on the right side EXCEPT:",
     "options": ["In a one way street.","When a vehicle in front is turning right.",
                 "When instructed to do so by a Police Officer.","All the above."], "correct": 3},
    {"id": 16, "title": "When a school bus is picking up or setting down passengers:",
     "options": ["All vehicles must stop until the school bus is no longer setting down passengers.",
                 "Vehicles must slow down and cautiously make their way around the bus.",
                 "Vehicles may pass at a safe distance to avoid collision.","None of the above."], "correct": 0},
    {"id": 17, "title": "A full driving license will be issued for:",
     "options": ["3 or 5 years","2 or 3 years","3 or 4 years","3 or 6 years"], "correct": 0},
    {"id": 18, "title": "Which of the following adults must wear seatbelts?",
     "options": ["Those seated in the front seat of a truck.","Those seated in the rear seat of a car.",
                 "Those seated in the front seat of a car.","All the above."], "correct": 3},
    {"id": 19, "title": "Which of the following is NOT an exception in law about wearing seatbelts?",
     "options": ["A driver performing a maneuver that includes reversing.",
                 "Those holding a medical certificate.",
                 "A woman who is more than 3 months pregnant.",
                 "Disabled persons wearing a disabled person's seatbelt."], "correct": 2},
    {"id": 20, "title": "What is the stopping distance at 30mph?",
     "options": ["60 feet","40 feet","75 feet","55 feet"], "correct": 0},
    {"id": 21, "title": "What is the stopping distance at 40mph?",
     "options": ["120 feet","100 feet","65 feet","90 feet"], "correct": 0},
    {"id": 22, "title": "What is the stopping distance at 50mph?",
     "options": ["120 feet","100 feet","80 feet","175 feet"], "correct": 3},
    {"id": 23, "title": "What times and places must you stop your vehicle?",
     "options": ["At a stop sign.",
                 "When a school bus is picking up or setting down passengers.",
                 "At a pedestrian crossing when someone is crossing.","All the above."], "correct": 3},
    {"id": 24, "title": "When driving past parked cars:",
     "options": ["Always drive on the right hand side of the road.",
                 "Drive normally as the cars are parked and not a bother.",
                 "Drive cautiously leaving enough room and look for car doors opening/pedestrians.",
                 "Drive closer to the parked cars so you never go into the other lane."], "correct": 2},
    {"id": 25, "title": "You are in the right lane approaching a roundabout wanting to turn left. You should:",
     "options": ["Indicate and go into the left lane and turn left at the roundabout.",
                 "Continue in the right lane and switch to the left lane after entering.",
                 "Put on your right indicator and go all the way around then exit left.",
                 "Do a three-point turn."], "correct": 0},

    # ── PPT SECTION 2 (Q26-50) ─────────────────
    {"id": 26, "title": "A provisional learner driver must only drive a vehicle when:",
     "options": ["On a minor road that is not busy.","On a major road that is busy.",
                 "When accompanied by a person holding a license for at least 1 year for that vehicle group.",
                 "When a full license is obtained."], "correct": 2},
    {"id": 27, "title": "When driving, a provisional learner driver is allowed to take:",
     "options": ["One passenger only along with the instructor.",
                 "Only the person supervising him or her.",
                 "Several persons as long as they have full licenses.",
                 "None of the above."], "correct": 1},
    {"id": 28, "title": "If you begin to feel drowsy or tired when driving, the correct thing to do is:",
     "options": ["Pull off the road at a safe place and rest.",
                 "Turn on the radio at a high level so you can stay alert.",
                 "Roll the windows down so the breeze can revive you.",
                 "Buy a coffee or energy drink and drink it."], "correct": 0},
    {"id": 29, "title": "Drivers should NOT reverse:",
     "options": ["Near a pre-school.","Into a main road.","Into a side road.",
                 "Where the center-line is unbroken."], "correct": 1},
    {"id": 30, "title": "You should NOT overtake:",
     "options": ["When the road is wet.",
                 "At the approach of a junction or a brow of a hill.",
                 "When your car needs servicing.","At night when it is raining."], "correct": 1},
    {"id": 31, "title": "The highest legal speed limit in the Cayman Islands is:",
     "options": ["70 Mph","55 Mph","40 Mph","50 Mph"], "correct": 3},
    {"id": 32, "title": 'What is the meaning of "Tailgating"?',
     "options": ["Using your car to hit a gate.","Driving a car without registration plates.",
                 "Driving too close to the center line on the road.",
                 "Driving or following too close behind vehicles."], "correct": 3},
    {"id": 33, "title": "Speed Bumps are:",
     "options": ["A traffic calming measure.","A hazard to road users.",
                 "Help traffic flow smoothly.","Increase road accidents."], "correct": 0},
    {"id": 34, "title": "If you stop at a pedestrian crossing and people refuse to cross, you should:",
     "options": ["Wave to them to cross as they may be gazing.",
                 "Call them across after you check your mirror.",
                 "Sound your horn to get their attention.","None of the above."], "correct": 3},
    {"id": 35, "title": "When driving on a single lane 2-way road and seeing an obstruction in your lane, you should:",
     "options": ["Pass in the other lane as the road belongs to everyone.",
                 "Wait until on-coming cars have passed then indicate and go around the obstruction.",
                 "Sound your horn as you maneuver around the obstruction.",
                 "Try to do a 3-point turn and choose another route."], "correct": 1},
    {"id": 36, "title": "When approaching a traffic light that has failed, you should:",
     "options": ["Be prepared to stop and give way to other vehicles.",
                 "Do not stop as this may cause unnecessary traffic congestion.",
                 "Speed up so that other vehicles will slow down and yield to you.",
                 "None of the above."], "correct": 0},
    {"id": 37, "title": "Who has the right of way at a crossroads where traffic-lights are not working?",
     "options": ["Bicycle and motorcycle riders.","Truck drivers.",
                 "Small cars.","No one has the right of way."], "correct": 3},
    {"id": 38, "title": "When driving past a line of parked cars you should:",
     "options": ["Drive cautiously.","Check for pedestrians walking between cars.",
                 "Check for car doors opening.","All the above."], "correct": 3},
    {"id": 39, "title": 'When a driver sees someone holding a "STOP CHILDREN CROSSING" sign, the driver should:',
     "options": ["Stop.","Slow down and drive cautiously across.",
                 "Check if there are any children and if not proceed.",
                 "Indicate and drive around the person holding the sign."], "correct": 0},
    {"id": 40, "title": "A solid white line down the centre of the road means a driver:",
     "options": ["Should not decrease their speed.",
                 "Can overtake if the person ahead is driving below the speed limit.",
                 "Should not overtake.","Lets the driver know a junction is up ahead."], "correct": 2},
    {"id": 41, "title": "A broken white line down the centre of the road means that a driver can overtake when it is safe to do so.",
     "options": ["True","False"], "correct": 0},
    {"id": 42, "title": "The centre lane along West Bay Road is:",
     "options": ["The lane drivers should use for overtaking.","A turning lane.",
                 "An extra lane for cars coming to town in the morning.",
                 "An extra lane for cars going towards West Bay in the evening."], "correct": 1},
    {"id": 43, "title": "A traffic calming measure in the road is an indicator to drivers to:",
     "options": ["Reduce your speed.","Maneuver around the calming device.",
                 "Watch out for pedestrians.","Stop."], "correct": 0},
    {"id": 44, "title": "It is safe to use a mobile phone when driving:",
     "options": ["Less than half the speed limit.",
                 "On a double lane road which is not congested.",
                 "When parked on the side of the road.","When there is an emergency."], "correct": 2},
    {"id": 45, "title": "What should a driver do when being followed by a Police car or ambulance with emergency lights?",
     "options": ["Reduce speed until the emergency vehicle has passed.",
                 "Speed up and keep control of the vehicle.",
                 "Turn on the hazard lights on the vehicle.",
                 "Pull over and stop to allow the vehicle to pass."], "correct": 3},
    {"id": 46, "title": "What is the age qualification to drive a motorcycle of an engine capacity exceeding 125cc?",
     "options": ["21 years","18 years","17 years","19 years"], "correct": 0},
    {"id": 47, "title": '"L" plates are only to be displayed when the vehicle is being driven by a Learner driver. True or False?',
     "options": ["True","False"], "correct": 0},
    {"id": 48, "title": "How often should a driver check the rear view mirror of the car?",
     "options": ["Every minute","Every 15 seconds",
                 "When moving off and when stopping only.","Every 12 seconds"], "correct": 1},
    {"id": 49, "title": "Which cars should you be more cautious about when approaching a roundabout?",
     "options": ["Cars approaching from the right.","Cars directly beside you.",
                 "Cars directly behind you.","Cars approaching from the left."], "correct": 0},
    {"id": 50, "title": "You are driving and you see a ball in the street, what should you do?",
     "options": ["Sound your horn so no one comes into the road to pick up the ball.",
                 "Drive at normal speed and continue on your journey.",
                 "Slow down and proceed with caution.",
                 "Use the car to slowly push the ball to the side of the road."], "correct": 2},

    # ── EXTRA QUESTIONS (from second source) ───
    {"id": 51, "title": "If there is one or two solid yellow lines at the centre of the road, you:",
     "options": ["Can pass as long as you can see at least 150 metres ahead of you and it is not by a corner",
                 "Can pass in the oncoming lane if it is safe to do so",
                 "Can pass only if the car in front is moving below the speed limit",
                 "Cannot pass in the oncoming lane"], "correct": 3},
    {"id": 52, "title": "What should you do if you must drive through a deep puddle?",
     "options": ["Drive through it as fast as you can",
                 "Drive through it slowly",
                 "Gently apply your brakes after you get through the puddle to dry them out",
                 "Avoid it entirely"], "correct": 2},
    {"id": 53, "title": "How should you be checking your blind spots?",
     "options": ["Ask your passenger in the backseat",
                 "Check your mirrors and turn your head",
                 "Check your rear view mirror",
                 "Check your sideview mirror"], "correct": 1},
    {"id": 54, "title": "Drinking any amount of alcohol is likely to:",
     "options": ["Give a false sense of confidence",
                 "Slow down your reactions to hazards",
                 "Worsen your judgment of speed",
                 "All of the above"], "correct": 3},
    {"id": 55, "title": "What should you keep in mind when making manoeuvres?",
     "options": ["Use your horn to warn other vehicles",
                 "Switch headlights from low to high beam to let other drivers know",
                 "Use only hand signals before the manoeuvre",
                 "Mirror/Observation - Signal - Manoeuvre (MSM)"], "correct": 3},
    {"id": 56, "title": "What must you have with you if you are towing a trailer?",
     "options": ["A license coupon",
                 "Documents of the goods you are carrying",
                 "Both A and B",
                 "None of the above"], "correct": 0},
    {"id": 57, "title": "Do cyclists have the same responsibilities and rights as drivers of vehicles?",
     "options": ["No","Only during daylight hours","Only in rural areas","Yes"], "correct": 3},
    {"id": 58, "title": "You should do the following when changing lanes:",
     "options": ["Check mirrors, check blind spot and proceed",
                 "Check mirrors, signal and proceed",
                 "Check mirrors, signal, check blind spot and proceed",
                 "Signal and proceed"], "correct": 2},
    {"id": 59, "title": "If a vehicle license is to be taken off-the-road for 3 months or more, the license may be suspended for that period.",
     "options": ["True","False"], "correct": 0},
    {"id": 60, "title": "You are expected to look into your rear-view mirror at least ______ times every minute.",
     "options": ["4","5","6","12"], "correct": 1},
    {"id": 61, "title": "If you see a potential hazard ahead, you should:",
     "options": ["Pull to the side until the hazard is gone",
                 "Take your foot off the accelerator and rest it on the brake pedal",
                 "Call a friend to warn them","None of the above"], "correct": 1},
    {"id": 62, "title": "What is the legal driving alcohol limit?",
     "options": ["50 mg/100 ml of blood","100 mg/100 ml of blood",
                 "150 mg/100 ml of blood","134 mg/100 ml of blood"], "correct": 1},
    {"id": 63, "title": "If you drive faster than other vehicles and continually pass other vehicles, you will:",
     "options": ["Still be late to get to your destination",
                 "Get to your destination more quickly and more safely",
                 "Help prevent traffic congestion",
                 "Increase your chance of an accident"], "correct": 3},
    {"id": 64, "title": "The holder of an International Driving License issued in another country may use that license freely in the Cayman Islands.",
     "options": ["True","False"], "correct": 0},
    {"id": 65, "title": "Some things to be attentive of on the side of the road are:",
     "options": ["Children and dogs","People in wheelchairs",
                 "People who are visually impaired","All of the above"], "correct": 3},
    {"id": 66, "title": "If you approach an intersection with no stop line, crosswalk or sidewalk, where do you stop?",
     "options": ["You stop a bit into the intersection to see traffic, pedestrians and cyclists",
                 "You stop at the edge of the intersection",
                 "You stop beside the stop sign",
                 "You stop right before the stop sign"], "correct": 1},
    {"id": 67, "title": "What is the penalty for the first offence of driving under the influence of alcohol or drugs?",
     "options": ["Fine of up to $500 or to imprisonment for up to 5 months or both",
                 "Fine of up to $1000 or to imprisonment for up to 6 months or both",
                 "Fine of up to $1500 or to imprisonment for up to 10 months or both",
                 "Fine of up to $2000 or to imprisonment for up to 12 months or both"], "correct": 1},
    {"id": 68, "title": "On a two-way road, what position must you be in to make a right turn?",
     "options": ["A little into the intersection","Before the stop sign",
                 "Beside the stop sign","Right before the edge of the intersection"], "correct": 3},
    {"id": 69, "title": "When are you required to report an accident to the police?",
     "options": ["Damage greater than $1000","Someone has been injured or killed",
                 "All of the above","None of the above"], "correct": 2},
    {"id": 70, "title": "You are about to drive home. You feel very tired and have a severe headache. You should:",
     "options": ["Drive home but take a tablet for headaches",
                 "Drive home if you can stay awake for the journey",
                 "Wait for a short time then drive home slowly",
                 "Wait until you are fit and well before driving"], "correct": 3},
    {"id": 71, "title": "How to brake with Anti Lock Brakes (ABS)?",
     "options": ["Brake by pumping the brakes","Press the brake and steer right",
                 "Press the brakes and steer left",
                 "Apply the brakes by pressing hard and firmly"], "correct": 3},
    {"id": 72, "title": "What is the general rule at a junction with no markings or signs?",
     "options": ["There are no rules since there are no markings or signs",
                 "You can cross the junction freely",
                 "Give way to traffic to your left",
                 "Give way to traffic to your right"], "correct": 3},
    {"id": 73, "title": "If you are a new resident to the island, you must obtain a Cayman license within ___ months of arrival.",
     "options": ["1","2","3","6"], "correct": 3},
    {"id": 74, "title": "What is important when braking due to an emergency?",
     "options": ["Brake harshly to lock the front tires","Sound your horn",
                 "Holding the steering wheel with both hands","All of the above"], "correct": 2},
    {"id": 75, "title": "What are good things to do when backing up?",
     "options": ["Back into parking spots so you can drive forward when leaving",
                 "Do a 360 degree vision check using shoulder checks and mirrors",
                 "Walk around the back of the vehicle if stopped for some time",
                 "All of the above"], "correct": 3},
    {"id": 76, "title": "To what direction should you turn the front wheels when parking uphill?",
     "options": ["Toward the kerb","Pointing forward","Away from the kerb","None of the above"], "correct": 2},
    {"id": 77, "title": "If there is a vehicle stopped in front of a crosswalk on a multi-lane road, you should:",
     "options": ["Honk at the vehicle","Pass the vehicle if it is on the left side only",
                 "Pass the vehicle if it is on the right side only",
                 "Stop before passing to ensure there are no pedestrians in the crosswalk"], "correct": 3},
    {"id": 78, "title": "When driving behind a slow-moving truck going uphill, you should:",
     "options": ["Be patient","Honk to make the driver speed up",
                 "Pass on the shoulder","Tailgate"], "correct": 0},
    {"id": 79, "title": "What are the recommended breaks/rests while driving?",
     "options": ["15 minutes every 2 hours of driving","15 minutes every 4 hours of driving",
                 "30 minutes every 2 hours of driving","30 minutes every 4 hours of driving"], "correct": 0},
    {"id": 80, "title": "If someone is tailgating you, you should:",
     "options": ["Decrease your speed slightly to create more room in front",
                 "Pull to the side to let the tailgater pass",
                 "Switch into another lane","All of the above"], "correct": 3},
    {"id": 81, "title": "If a visitor is to use a privately owned vehicle, a Visitor's Permit does not need to be obtained.",
     "options": ["True","False"], "correct": 1},
    {"id": 82, "title": "Which of the following is true about your driving license?",
     "options": ["You are allowed more than one copy of your license",
                 "You are allowed to lend your license to friends",
                 "All of the above","None of the above"], "correct": 3},
    {"id": 83, "title": "If you see farm animals when driving, you should:",
     "options": ["Follow the directions from the person tending to the animals",
                 "Get out the car and charge the animals",
                 "Honk until the animals cross the road",
                 "Swerve to avoid the animals"], "correct": 0},
    {"id": 84, "title": "An emergency vehicle is approaching behind you, what should you do?",
     "options": ["Slow down, pull to the side of the road and be prepared to stop",
                 "Turn on your hazard lights",
                 "Use your horn to signal other vehicles",
                 "Bring your vehicle to an immediate stop"], "correct": 0},
    {"id": 85, "title": "While driving on a road, are you allowed to drink alcoholic beverages?",
     "options": ["Never",
                 "No, unless another driver can take your place",
                 "Yes, as long as your blood alcohol concentration is within the legal limit",
                 "Yes, if you are very close to your destination"], "correct": 0},
    {"id": 86, "title": "What should you do if you go into a curve too quickly?",
     "options": ["Ease off the gas pedal, then speed up slightly after gaining some traction",
                 "Pull the emergency brake and steer into the curve",
                 "Pump the brakes and gradually slow down until you can stop",
                 "Slam on the brakes"], "correct": 0},
    {"id": 87, "title": "Scanning the road ahead helps drivers to:",
     "options": ["See cars and people up ahead","See hazards up ahead",
                 "See road signs or driving information","All of the above"], "correct": 3},
    {"id": 88, "title": "Get into the habit of checking your car on a frequent basis for:",
     "options": ["Dead light bulbs (e.g. rear brake lights)","Tyre pressure",
                 "Oil and fluid levels","All of the above"], "correct": 3},
    {"id": 89, "title": "All adults in cars must wear seatbelts, with the exception of:",
     "options": ["A driver who is performing a manoeuvre including reversing",
                 "Those holding a medical certificate",
                 "Disabled persons wearing a disabled persons seatbelt",
                 "All of the above"], "correct": 3},
    {"id": 90, "title": "When a vehicle is licensed, the owner must show that it has been:",
     "options": ["Properly registered in his name","Passed an inspection test",
                 "Insured","All of the above"], "correct": 3},
    {"id": 91, "title": "If convicted of reckless driving, what could be the penalty?",
     "options": ["$500 fine and/or imprisonment for 1 year or both",
                 "$1000 fine and/or imprisonment for 1 year, or both",
                 "$1500 fine and/or imprisonment for 2 years, or both",
                 "$2000 fine and/or imprisonment for 2 years, or both"], "correct": 1},
    {"id": 92, "title": "What is the speed limit near a school zone?",
     "options": ["10 mph","15 mph","30 mph","45 mph"], "correct": 1},
    {"id": 93, "title": "What must you do when a school bus is flashing red lights?",
     "options": ["Reduce your speed to 15 mph",
                 "Proceed with caution at a moderate speed",
                 "Overtake the bus only from the left side",
                 "You must come to a halt until the lights are no longer flashing"], "correct": 3},
    {"id": 94, "title": "If you pull just slightly into another lane to pass a cyclist:",
     "options": ["You should mirror check, signal and shoulder check",
                 "You are doing it wrong and should pass within the same lane as the cyclist",
                 "You are doing something illegal","None of the above"], "correct": 0},
    {"id": 95, "title": "What is good practice when there is a vulnerable road user crossing the road?",
     "options": ["Be patient, give them enough time to cross the road",
                 "Signal them to hurry up and cross the road",
                 "Use your horn to let them know you are there waiting",
                 "Rev your engine to get them to speed up"], "correct": 0},
    {"id": 96, "title": "When going down a steep hill, you should:",
     "options": ["Put your car into neutral","Shift to a higher gear",
                 "Shift to a lower gear","Slam on the brakes"], "correct": 2},
    {"id": 97, "title": "Remember before turning, or making a manoeuvre:",
     "options": ["Indicator, make the manoeuvre, then check mirror",
                 "Indicator, check mirror, then make the manoeuvre",
                 "Make the manoeuvre, check mirror, then indicator",
                 "Check mirror, indicator, then make the manoeuvre"], "correct": 3},
    {"id": 98, "title": "When driving through a construction zone, you should:",
     "options": ["Honk at drivers that slow down","Maintain a steady speed",
                 "Slow down and proceed with caution","Speed up"], "correct": 2},
    {"id": 99, "title": "What should you do when pulling away from the curb?",
     "options": ["Check your rear-view mirror, then pull out when safe",
                 "Shoulder check, then pull out when safe",
                 "Signal, check your rear-view mirror, then pull out when safe",
                 "Signal, shoulder check, then pull out when safe"], "correct": 3},
    {"id": 100, "title": "In bad weather, what is the best speed to drive?",
     "options": ["The speed limit","The speed with which you will be safe",
                 "45 mph","None of the above"], "correct": 1},
    {"id": 101, "title": "How can you reduce fuel consumption when driving?",
     "options": ["Engage in rapid acceleration whenever possible",
                 "Have your tires properly inflated",
                 "Leave the engine running while parked",
                 "All of the above"], "correct": 1},
    {"id": 102, "title": "When driving in the fog, you should use your:",
     "options": ["Fog lights only","High beams","Low beams","Windshield wipers"], "correct": 2},
    {"id": 103, "title": "What should you do if you think you are going to fall asleep at the wheel?",
     "options": ["Blast the radio","Drink coffee",
                 "Turn off the road and take a nap in a safe spot",
                 "Turn up the air conditioning"], "correct": 2},
    {"id": 104, "title": "What is the braking distance if you are driving at 50 mph under normal road conditions?",
     "options": ["25 feet","50 feet","100 feet","125 feet"], "correct": 3},
    {"id": 105, "title": "Motorcycle sidecars may be imported into the Cayman Islands.",
     "options": ["True","False"], "correct": 1},
    {"id": 106, "title": "What is the time limit within which you must pay a ticket after this is served?",
     "options": ["7 days","14 days","28 days","There is no time limit"], "correct": 2},
    {"id": 107, "title": "At a four-way stop intersection, the driver must yield the right-of-way to:",
     "options": ["Any driver who is turning left","Any driver who is turning right",
                 "Vehicles on the left or vehicles already stopped",
                 "Vehicles on the right or vehicles already stopped"], "correct": 3},
    {"id": 108, "title": "When can you make a left turn at a red light?",
     "options": ["After coming to a complete stop and yielding for pedestrians and traffic",
                 "After slowing down to check for oncoming traffic",
                 "Anytime there are no signs prohibiting a left turn on a red light",
                 "B and C"], "correct": 0},
    {"id": 109, "title": "Everyone who applies for a driving test knowing they have been disqualified from driving in a foreign country is committing an extremely serious offence.",
     "options": ["True","False"], "correct": 0},
    {"id": 110, "title": "When making a right-hand turn, why should you never pull into the left-hand side of the road first?",
     "options": ["Other drivers will not have space to continue",
                 "Because you can't stop on the left hand side of the road",
                 "Other users may not be able to see you",
                 "It confuses other road users and they may think you are making another manoeuvre"], "correct": 3},
    {"id": 111, "title": "Generally, if you hear the siren of an emergency vehicle you should:",
     "options": ["Immediately come to a stop",
                 "Let the emergency vehicle pass and follow it closely behind",
                 "Pull over to the left until the emergency vehicle passes"], "correct": 2},
    {"id": 112, "title": "What is one acceptable instance where you can flash your headlights?",
     "options": ["To warn other road users of works ahead",
                 "To signal the driver in front of you to come to a stop",
                 "To let other road users know you are there",
                 "To dazzle the driver in front of you"], "correct": 2},
    {"id": 113, "title": "What should you do if you are making a right-hand turn and there is traffic coming from the opposite direction?",
     "options": ["Keep moving, the other vehicles should stop",
                 "Come to a stop before making the turn",
                 "Signal them that you are making a turn so they can stop",
                 "Use your horn to let them know you intend to make a turn"], "correct": 1},
    {"id": 114, "title": "As you approach a crosswalk, you notice that pedestrians are crossing the road. It is illegal to:",
     "options": ["Continue driving","Drop passengers close to the crosswalk",
                 "Signal for the pedestrians to continue crossing","Stop for them"], "correct": 0},
    {"id": 115, "title": "What style of driving causes increased risk to everyone?",
     "options": ["Competitive","Considerate","Defensive","Responsible"], "correct": 0},
    {"id": 116, "title": "When is it safe to overtake on a bend?",
     "options": ["When there is enough space to pass the other vehicle",
                 "You must not overtake on a bend",
                 "When the other driver is aware you are overtaking",
                 "When you signal other vehicles of your intention"], "correct": 1},
    {"id": 117, "title": "When passing vehicles in the left lane (on a multi-lane road), this is:",
     "options": ["Not permitted",
                 "Permitted on any highway or road",
                 "Permitted when the street or highway has two or more lanes in your direction",
                 "Permitted only if driving on the shoulder to pass"], "correct": 2},
    {"id": 118, "title": "What should you do when a large animal is in your path and you cannot stop in time?",
     "options": ["Brake firmly",
                 "Let up on the brake pedal just before hitting the animal to reduce windshield impact",
                 "Try to strike the large animal at an angle",
                 "All of the above"], "correct": 3},
    {"id": 119, "title": "You are in a tunnel. Your vehicle is on fire and you cannot drive it. What should you do?",
     "options": ["Switch on hazard warning lights","Try and put out the fire",
                 "All of the above","None of the above"], "correct": 2},
    {"id": 120, "title": "If a vehicle license is to be taken off-the-road for 3 months or more, the license may be suspended for that period when the vehicle is not being used.",
     "options": ["True","False"], "correct": 0},
]

LETTERS = ["A", "B", "C", "D"]
PASS_RATE = 0.80
QUESTIONS_PER_TEST = 25

# ─────────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────────

@app.route("/")
def home():
    session.clear()
    return render_template("home.html", total=len(ALL_QUESTIONS))


@app.route("/start", methods=["POST"])
def start():
    mode = request.form.get("mode", "random")
    if mode == "random":
        selected = random.sample(ALL_QUESTIONS, QUESTIONS_PER_TEST)
    elif mode == "ppt1":
        selected = [q for q in ALL_QUESTIONS if q["id"] <= 25]
    elif mode == "ppt2":
        selected = [q for q in ALL_QUESTIONS if 26 <= q["id"] <= 50]
    elif mode == "extra":
        selected = [q for q in ALL_QUESTIONS if q["id"] > 50][:QUESTIONS_PER_TEST]
    elif mode == "all":
        selected = random.sample(ALL_QUESTIONS, min(40, len(ALL_QUESTIONS)))
    else:
        selected = random.sample(ALL_QUESTIONS, QUESTIONS_PER_TEST)

    session["questions"] = selected
    session["current"] = 0
    session["score"] = 0
    session["answers"] = []
    session["mode"] = mode
    return redirect(url_for("question"))


@app.route("/question")
def question():
    questions = session.get("questions", [])
    current = session.get("current", 0)
    if current >= len(questions):
        return redirect(url_for("results"))
    q = questions[current]
    return render_template(
        "question.html",
        q=q,
        current=current + 1,
        total=len(questions),
        score=session.get("score", 0),
        letters=LETTERS,
        pct=round((current / len(questions)) * 100),
    )


@app.route("/answer", methods=["POST"])
def answer():
    questions = session.get("questions", [])
    current = session.get("current", 0)
    selected = int(request.form.get("selected", -1))
    if current >= len(questions):
        return redirect(url_for("results"))

    q = questions[current]
    correct = q["correct"]
    is_correct = selected == correct

    if is_correct:
        session["score"] = session.get("score", 0) + 1

    answers = session.get("answers", [])
    answers.append({
        "qid": q["id"],
        "title": q["title"],
        "selected": selected,
        "correct": correct,
        "options": q["options"],
        "is_correct": is_correct,
    })
    session["answers"] = answers
    session["current"] = current + 1

    return render_template(
        "feedback.html",
        q=q,
        selected=selected,
        correct=correct,
        is_correct=is_correct,
        current=current + 1,
        total=len(questions),
        score=session.get("score", 0),
        letters=LETTERS,
        is_last=(current + 1 >= len(questions)),
    )


@app.route("/results")
def results():
    questions = session.get("questions", [])
    answers = session.get("answers", [])
    score = session.get("score", 0)
    total = len(questions)
    pass_needed = round(total * PASS_RATE)
    passed = score >= pass_needed
    pct = round((score / total) * 100) if total else 0
    return render_template(
        "results.html",
        score=score,
        total=total,
        pass_needed=pass_needed,
        passed=passed,
        pct=pct,
        answers=answers,
        letters=LETTERS,
    )

@app.route('/robots.txt')
def robots():
    return send_from_directory(app.static_folder, 'robots.txt')
 
# ─── sitemap.xml (already working via /static/) ───────────────
@app.route('/sitemap.xml')
def sitemap():
    return send_from_directory(app.static_folder, 'sitemap.xml')


if __name__ == "__main__":
    app.run(debug=True, port=5000)
